@echo off
echo Starting SkyBrain Development Server...
wsl -d Ubuntu -e bash -c "cd '/mnt/c/Rakesh Work/SkyBrain Official/Cursor/claude code/mind-shift-frontier-web-main/SkyBrain Website' && npm run dev"